### ISSUE TITLE
"oversized data" with 2.2.2

### ISSUE THREAD

**Issue by jmcnevin** [Consensys-Incorporated/quorum#674]
#### System information

Geth version: 2.2.2

OS & Version: Ubuntu 18.04

#### Expected behaviour

After upgrading validators, using the same genesis block, the ability to submit transactions should not be affected.

#### Actual behaviour

After upgrading validators, all submitted transactions are failing with "oversized data" error.  Fix is to modify the genesis block to add config.txnSizeLimit: 64.

#### Steps to reproduce the behaviour

Initialize a network using 2.2.1, then upgrade validator set to 2.2.2.

**Comment by jbhurat** [comment]
Hi @jmcnevin, can you provide more details on your setup. Was the network was already running before the upgrading the validator set to 2.2.2

**Comment by jmcnevin** [comment]
Yes, this network was running on 2.2.1.  I only upgraded quorum and left everything else untouched.

I can also verify that this problem returns if I remove `txnSizeLimit` from the genesis block and restart the network.

Genesis block:

```yaml
{
  "config": {
    "chainId": 19827658,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "istanbul": {
      "epoch": 30000,
      "policy": 0
    },
    "isQuorum": true
  },
  "nonce": "0x0",
  "timestamp": "0x5a7fd1b0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f89af8549408e9e9cd8ca072b435832d00d3a266f6cf7444ac941daf95f9c9129c44c888345ae0ee4bde9152b3fa9446f4512d6cddb8c776046103b1022d5b33058ebd94fdbd79619bee02829e53b0331062ece15367676fb8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "08e9e9cd8ca072b435832d00d3a266f6cf7444ac": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
    "1daf95f9c9129c44c888345ae0ee4bde9152b3fa": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
    "46f4512d6cddb8c776046103b1022d5b33058ebd": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
    "fdbd79619bee02829e53b0331062ece15367676f": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

Command line arguments:

```
--datadir /data/geth --emitcheckpoints --gasprice 0 --nat none --networkid 19827658 --permissioned --port 30303 --syncmode full --targetgaslimit 700000000 --metrics --mine
```
