### ISSUE TITLE
Validator crashes in 2.2.2

### ISSUE THREAD

**Issue by jmcnevin** [Consensys-Incorporated/quorum#676]
#### System information

Geth version: 2.2.2

OS & Version: Linux

#### Expected behaviour

Validators should not crash.

#### Actual behaviour

With IBFT, under load, we are able to get validators to crash with errors such as `fatal error: concurrent map writes`.

#### Steps to reproduce the behaviour

We have a four-node validator set with validators running the following options:

```
--datadir /data/geth --emitcheckpoints --nat none --networkid 19827658 --permissioned --port 30303 --syncmode full --gcmode archive --nousb  --metrics --mine --miner.gasprice 0 --miner.gaslimit 700000000
```

#### Backtrace

[dump.txt](https://github.com/jpmorganchase/quorum/files/3044505/dump.txt)

**Comment by jbhurat** [comment]
Hi @jmcnevin, can you please paste your genesis.json

**Comment by jmcnevin** [comment]
```yaml
{
  "config": {
    "chainId": 19827658,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "istanbul": {
      "epoch": 30000,
      "policy": 0
    },
    "isQuorum": true,
    "txnSizeLimit": 64
  },
  "nonce": "0x0",
  "timestamp": "0x5a7fd1b0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f89af8549408e9e9cd8ca072b435832d00d3a266f6cf7444ac941daf95f9c9129c44c888345ae0ee4bde9152b3fa9446f4512d6cddb8c776046103b1022d5b33058ebd94fdbd79619bee02829e53b0331062ece15367676fb8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "08e9e9cd8ca072b435832d00d3a266f6cf7444ac": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
    "1daf95f9c9129c44c888345ae0ee4bde9152b3fa": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
    "46f4512d6cddb8c776046103b1022d5b33058ebd": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
    "fdbd79619bee02829e53b0331062ece15367676f": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```
